name: Develop

on:
  push:
    branches: [develop]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [develop]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'

jobs:
  basic:
    uses: zysec-ai/.github/.github/workflows/_reusable-basic-check.yml@develop
