name: validate-branch-flow

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  pull-requests: read
  contents: read

jobs:
  branch-checks:
    uses: ./.github/workflows/_reusable-branch-flow-check.yml
    secrets: inherit
