name: Needs Rebase

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  needs-rebase:
    name: Check for merge conflicts
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'bot-skip')"
    steps:
      - name: Label conflicting PRs
        uses: eps1lon/actions-label-merge-conflict@b8bf8341285ec9a4567d4318ba474fee998a6919  # v2.0.1
        with:
          repoToken: "${{ secrets.ORG_ADMIN_TOKEN || github.token }}"
          dirtyLabel: "needs-rebase"
          removeOnDirtyLabel: ""
          commentOnDirty: |
            ⚠️ This PR has a merge conflict and can no longer be merged automatically.
            Please rebase onto `${{ github.base_ref }}` and resolve any conflicts.
          commentOnClean: ""
